In [1]:
#importing library files

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [71]:
#reading the file
data=pd.read_csv("classification_2.csv",sep=',')
data.columns =  ['age', 'workarea', 'ID', 
           'education', 'education-year', 
           'marital-status', 'occupation', 
           'relationship', 'race', 'sex', 
           'capital-gain', 'capital-loss', 
           'hours-per-week', 'native-country', 
           'salary']

data.head()


age           workarea      ID   education  education-year  \
0   50   Self-emp-not-inc   83311   Bachelors              13   
1   38            Private  215646     HS-grad               9   
2   53            Private  234721        11th               7   
3   28            Private  338409   Bachelors              13   
4   37            Private  284582     Masters              14   

        marital-status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

In [72]:
y = data["salary"]
dataset= data[['age','education-year','capital-gain','capital-loss','hours-per-week']]

In [73]:
y.replace([' <=50K',' >50K'],[0,1],inplace=True)

In [74]:
def normalize(values):
    return (values - values.min())/(values.max() - values.min())

cols=['age','education-year','capital-gain','capital-loss','hours-per-week']
data[cols] = data[cols].apply(normalize)

X=data[cols]
X=np.array(X)
X

array([[0.45205479, 0.8       , 0.        , 0.        , 0.12244898],
       [0.28767123, 0.53333333, 0.        , 0.        , 0.39795918],
       [0.49315068, 0.4       , 0.        , 0.        , 0.39795918],
       ...,
       [0.56164384, 0.53333333, 0.        , 0.        , 0.39795918],
       [0.06849315, 0.53333333, 0.        , 0.        , 0.19387755],
       [0.47945205, 0.53333333, 0.1502415 , 0.        , 0.39795918]])

In [99]:
train_index = int(0.8 * len(X))
X_train, X_test = X[:train_index], X[train_index:]
y_train, y_test = y[:train_index], y[train_index:]

In [100]:
X_train

array([[0.45205479, 0.8       , 0.        , 0.        , 0.12244898],
       [0.28767123, 0.53333333, 0.        , 0.        , 0.39795918],
       [0.49315068, 0.4       , 0.        , 0.        , 0.39795918],
       ...,
       [0.26027397, 0.73333333, 0.        , 0.        , 0.39795918],
       [0.32876712, 0.8       , 0.        , 0.        , 0.39795918],
       [0.17808219, 0.6       , 0.        , 0.        , 0.39795918]])

In [101]:
a=0
b=0
c=0
d=0
e=0
f=0

#learning rate
L = 0.01 
#epoch for mininum iterations to find minimum rss/mse
epochs = 1000  

#number of observations
n = float(len(X_train)) 

for i in range(epochs): 
    z = a+b*X_train[:,0]+c*X_train[:,1]+d*X_train[:,2]+e*X_train[:,3]+f*X_train[:,4]
    h=1/(1+np.exp(-z))
    
    D_a = (1/n) * sum(h-y_train)
    D_b = (1/n) * sum(X_train[:,0] * (h-y_train))
    D_c = (1/n) * sum(X_train[:,1] * (h-y_train)) 
    D_d = (1/n) * sum(X_train[:,2] * (h-y_train))   
    D_e = (1/n) * sum(X_train[:,3] * (h-y_train))
    D_f = (1/n) * sum(X_train[:,4] * (h-y_train))
   
    a = a - L * D_a  
    b = b - L * D_b
    c = c - L * D_c  
    d = d - L * D_d
    e = e - L * D_e
    f = f - L * D_f
    
    
print (a,b,c,d,e,f)

-0.7997143092468842 -0.04705084090153804 -0.22738034399605542 0.0633415756380022 0.04303642750219635 -0.19268244957871994


In [102]:
z1 = a+b*X_train[:,0]+c*X_train[:,1]+d*X_train[:,2]+e*X_train[:,3]+f*X_train[:,4]
h_result=1/(1+np.exp(-z1))


In [103]:
y_pred=[]

for i in range(len(h_result)):
    if h_result[i]>0.5:
        y_pred.append(1)
    elif h_result[i]<0.5:
        y_pred.append(0)

In [108]:
h_result

array([0.26376673, 0.26674532, 0.27080358, ..., 0.25819223, 0.25468735,
       0.26479349])

In [113]:
def accuracy(y_true, y_pred):
    accuracy = np.mean(y_pred == y_true) 
    return accuracy
accuracy(y_train,y_pred)

0.7604038697788698